# Generated by Django 4.0.5 on 2022-07-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('Publishing_Date', models.DateTimeField()),
                ('link', models.URLField()),
                ('image', models.URLField()),
                ('Podcast_Name', models.CharField(max_length=500)),
                ('guid', models.CharField(max_length=50)),
            ],
        ),
    ]
